framework:
    default_locale: '%locale%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - '%locale%'
# framework:
#     translator:
#         default_path: '%kernel.project_dir%/translations'
#         fallbacks: [ "fr" ]